# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 09:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampOfExpense', models.DateTimeField(auto_now_add=True)),
                ('expense_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'INR'), ('USD', 'USD')], default='XYZ', editable=False, max_length=3)),
                ('expense', djmoney.models.fields.MoneyField(currency_choices=(('INR', 'INR'), ('USD', 'USD')), decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Client')),
            ],
        ),
    ]
